sudo: required
language: java
addons:
  apt:
    packages:
      - net-tools
services:
  - docker
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
script: 
  - ./gradlew --refresh-dependencies shadowJar
  - docker build -t hazelcast-docker-swarm-discovery-spi-test -f Test.Dockerfile .
  - docker swarm init
  - docker network create -d overlay hazelcast-docker-swarm-discovery-spi-test
  - docker service create --network hazelcast-docker-swarm-discovery-spi-test --name hazelcast-docker-swarm-discovery-spi-test -e "DOCKER_HOST=http://192.168.0.148:2376" hazelcast-docker-swarm-discovery-spi-test java -DdockerNetworkNames=hazelcast-docker-swarm-discovery-spi-test -DdockerServiceNames=hazelcast-docker-swarm-discovery-spi-test -DhazelcastPeerPort=5701 -jar /test.jar
  - docker service ls
  - docker ps
  - docker service hazelcast-docker-swarm-discovery-spi-test stop
  - ifconfig -a
  - export TEST=1
  - echo $TEST
jdk:
  - oraclejdk8
