sudo: required
language: java

addons:
  apt:
    packages:
      - net-tools

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:

script: 
  - ./gradlew --refresh-dependencies shadowJar
  - docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 2376:2375 bobrik/socat TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
  - docker build -t hazelcast-docker-swarm-discovery-spi-test -f Test.Dockerfile .
  - docker images 
  - docker swarm init
  - docker node ls
  - docker network create -d overlay hazelcast-docker-swarm-discovery-spi-test
  - export MY_IP=`ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`
  - echo $MY_IP
  - docker service create --network hazelcast-docker-swarm-discovery-spi-test --name hazelcast-docker-swarm-discovery-spi-test -e "DOCKER_HOST=http://$MY_IP:2376" hazelcast-docker-swarm-discovery-spi-test java -DdockerNetworkNames=hazelcast-docker-swarm-discovery-spi-test -DdockerServiceNames=hazelcast-docker-swarm-discovery-spi-test -DhazelcastPeerPort=5701 -jar /test.jar
  - docker service ls
  - sleep 10
  - docker ps
  - export CONTAINER1_ID=`docker ps -f "name=hazelcast-docker-swarm-discovery-spi-test.1" --format "{{.ID}}"`
  - docker logs $CONTAINER1_ID
  - docker service scale hazelcast-docker-swarm-discovery-spi-test=10
  - sleep 30
  - docker ps
  - docker logs $CONTAINER1_ID 
  - export CONTAINER10_ID=`docker ps -f "name=hazelcast-docker-swarm-discovery-spi-test.10" --format "{{.ID}}"`
  - docker logs $CONTAINER10_ID 
  - export MEMBER_TOTAL=`docker logs $CONTAINER1_ID 2>&1 | grep "Members \[10\]"`
  - echo $MEMBER_TOTAL
  - if [ "$MEMBER_TOTAL" = 'Members [10]' ]; then echo "OK"; else exit 1; fi
  - docker service rm hazelcast-docker-swarm-discovery-spi-test
  
jdk:
  - oraclejdk8
